import {StyleSheet} from 'react-native';
import {Colors} from '../../../utils/Colors';
import {hp} from '../../../utils/responsivesness';
import fonts from '../../../utils/Fonts';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: fonts.UrbanistBold,
  },
  coverImage: {
    width: '100%',
    height: 245,
    resizeMode: 'cover',
  },
  header: {
    position: 'absolute',
    top: 16,
    left: 10,
    right: 0,
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingTop: 12,
  },

  shareButton: {
    width: 41,
    height: 41,
    borderRadius: 20.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.darkInputBg,
  },

  leftColumn: {
    flex: 1,
    gap: 15,
    flexDirection: 'row',
  },
  challengeTitle: {
    fontSize: 24,
    marginBottom: 8,
    paddingHorizontal: 20,
    marginTop: 12,
    fontFamily: fonts.UrbanistBold,
  },
  separator: {
    height: 1,
    marginVertical: 16,
    marginHorizontal: 20,
  },
  row: {
    gap: 15,
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  subtitle: {
    fontSize: 17,
    marginTop: hp(2),
    fontFamily: fonts.UrbanistSemiBold,
  },
  subtitleValue: {
    fontSize: 15,
    marginTop: hp(2.4),
    fontFamily: fonts.UrbanistRegular,
  },
  rulesTitle: {
    fontSize: 18,
    marginBottom: 8,
    paddingHorizontal: 20,
    fontFamily: fonts.UrbanistSemiBold,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  ruleText: {
    fontSize: 16,
    fontFamily: fonts.UrbanistRegular,
  },
  dateValue: {
    fontSize: 18,
    marginTop: hp(2),
    fontFamily: fonts.UrbanistRegular,
  },
  daysLeft: {
    fontSize: 14,
    color: Colors.red,
    marginTop: hp(2.5),
    fontFamily: fonts.UrbanistMedium,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(6),
    marginHorizontal: 20,
    marginTop: hp(2),
  },
  progressBackground: {
    width: '100%',
    height: 10,
    borderRadius: 121.6,
    marginRight: 8,
  },
  progressFill: {
    height: 10,
    backgroundColor: Colors.Yellow,
    borderRadius: 121,
  },
  loaderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  icon: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
  },
  calendarContainer: {
    width: '90%',
    minHeight: 350,
    borderRadius: 20,
    padding: 15,
    alignSelf: 'center',
    marginBottom: 20,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 8,
    borderRadius: 8,
    gap: 8,
  },
  arrowButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
    marginLeft: 8,
  },
  monthText: {
    fontSize: 22,
    fontFamily: fonts.UrbanistSemiBold,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  weekday: {
    width: 36,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: fonts.UrbanistRegular,
    marginHorizontal: 2,
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    paddingHorizontal: 2,
  },
  dateCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    marginHorizontal: 2,
  },
  dateActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  dateText: {
    fontSize: 18,
    fontFamily: fonts.UrbanistBold,
  },
  viewAllText: {
    fontSize: 16,
    marginBottom: 20,
    fontFamily: fonts.UrbanistSemiBold,
  },
  statusCard: {
    width: '90%',
    height: 57,
    borderRadius: 21,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  statusText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: fonts.UrbanistSemiBold,
  },
  progressTitle: {
    fontSize: 18,
    marginLeft: 20,
    marginBottom: 10,
    fontFamily: fonts.UrbanistBold,
  },
  upwardMonthList: {
    position: 'absolute',
    width: '90%',
    bottom: '0%',
    left: 20,
    right: 0,
    padding: 10,
    borderRadius: 10,
    zIndex: 999,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    alignSelf: 'center',
  },
  monthOption: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  date: {
    fontSize: 15,
    paddingVertical: 4,
    fontFamily: fonts.UrbanistMedium,
  },
  avatarGroup: {
    flexDirection: 'row',
    marginTop: hp(2),
    marginRight: hp(3),
  },
  avatarWrapper: {
    width: 27,
    height: 27,
    marginLeft: -10,
    borderWidth: 1.52,
    borderColor: '#F4F4FC',
    borderRadius: 27 / 2,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 27,
    height: 27,
    borderRadius: 27 / 2,
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '85%',
    maxHeight: '70%',
    borderRadius: 16,
    paddingVertical: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: fonts.UrbanistBold,
  },
  closeButton: {
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: 30,
    height: 30,
  },
  closeButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalScrollView: {
    maxHeight: 300,
  },
  monthOption: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthText: {
    fontSize: 16,
    fontFamily: fonts.UrbanistMedium,
  },
  yearSelector: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    marginBottom: 10,
  },
  yearOption: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    minWidth: 70,
  },
});
