import {StyleSheet} from 'react-native';
import {hp, wp, rfs, rwp, rhp} from '../../../utils/responsivesness';
import fonts from '../../../utils/Fonts';
import {Colors} from '../../../utils/Colors';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
  },
  title: {
    fontSize: rfs(24),
    fontFamily: fonts.UrbanistBold,
    marginBottom: hp(2),
    paddingHorizontal: 20,
  },
  subtitle: {
    fontFamily: fonts.UrbanistBold,
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 25.2,
    letterSpacing: 0.2,
    color: '#FFFFFF',
    marginTop: rhp(10),
    marginBottom: rhp(8),
    paddingHorizontal: 20,
  },
  helpText: {
    fontFamily: fonts.UrbanistRegular,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: '#F5F5F5',
    marginBottom: rhp(14),
    paddingHorizontal: 20,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#1F1F1F',
    marginBottom: 16,
    marginHorizontal: 20,
  },
  dropdownText: {
    fontFamily: fonts.UrbanistSemiBold,
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 22,
    color: '#9E9E9E',
  },
  labelText: {
    fontFamily: fonts.UrbanistRegular,
    fontSize: 18,
    letterSpacing: 0.2,
    paddingHorizontal: 20,
    marginBottom: hp(2),
  },
  dropdownTextSelected: {
    fontFamily: fonts.UrbanistSemiBold,
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  sliderTrack: {
    width: '90%',
    height: 24,
    justifyContent: 'center',
    position: 'relative',
    alignSelf: 'center',
    marginTop: 34,
    marginBottom: 12,
  },
  fullTrack: {
    position: 'absolute',
    width: '100%',
    height: 19,
    borderRadius: 138,
    backgroundColor: '#2F7ABE',
    opacity: 0.2,
    top: '50%',
    transform: [{translateY: -3}],
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientLine: {
    position: 'absolute',
    height: 19,
    borderRadius: 138,
    top: '50%',
    left: 0,
    transform: [{translateY: -3}],
  },
  slider: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    marginTop: 12,
  },
  sliderLabel: {
    color: '#FFFFFF',
    fontFamily: fonts.UrbanistBold,
    fontSize: 14,
    marginBottom: rhp(6),
    paddingHorizontal: 20,
  },
  thumbLabel: {
    position: 'absolute',
    top: -42,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    marginLeft: -10,
  },
  thumbLabelText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },

  tickRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(0.5),
    marginBottom: hp(2),
  },
  tickLabel: {
    fontSize: 10,
    fontFamily: fonts.UrbanistRegular,
    color: Colors.white,
    paddingHorizontal: 20,
  },
  uploadLabel: {
    fontSize: rfs(14),
    fontFamily: fonts.UrbanistSemiBold,
    marginTop: hp(4),
    marginBottom: hp(1),
    marginHorizontal: 20,
  },
  uploadInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1F1F1F',
    borderRadius: 12,
    padding: wp(4),
    marginBottom: rhp(20),
    marginHorizontal: 20,
  },
  uploadPlaceholder: {
    fontSize: 14,
    fontFamily: fonts.UrbanistSemiBold,
    color: '#9E9E9E',
  },
  uploadIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconDivider: {
    width: 1,
    height: rhp(20),
    backgroundColor: Colors.meduimgray,
    marginHorizontal: rwp(10),
  },
  bottomButtonWrapper: {
    paddingVertical: rhp(70),
    backgroundColor: 'transparent',
    marginBottom: 20,
  },
  reviewBox: {
    backgroundColor: '#1F1F1F',
    borderRadius: 12,
    height: 168,
    padding: rwp(8),
    marginTop: rhp(10),
    marginBottom: rhp(20),
    marginHorizontal: 20,
  },
  reviewLabel: {
    fontSize: rfs(12),
    fontFamily: fonts.UrbanistMedium,
    color: Colors.white,
    marginBottom: rhp(5),
  },
  reviewInput: {
    fontSize: 14,
    fontFamily: fonts.UrbanistSemiBold,
    color: Colors.white,
    minHeight: rhp(100),
    textAlignVertical: 'top',
  },
  selectedChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 15,
    paddingHorizontal: 20,
  },
  skillChip: {
    flexDirection: 'row',
    backgroundColor: Colors.darkCard,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignItems: 'center',
  },
  chipText: {
    color: Colors.white,
    marginRight: 8,
  },
  chipClose: {
    color: Colors.red,
  },
  remove: {
    position: 'absolute',
    top: 5,
    right: -16,
    padding: 2,
  },
  separater: {
    height: 1,
    width: '90%',
    marginVertical: 12,
    alignSelf: 'center',
  },
  fieldRow: {
    flexDirection: 'row',
    marginVertical: 10,
    flexWrap: 'wrap',
    paddingHorizontal: 10,
    marginLeft: 5,
    justifyContent: 'center',
  },

  fieldBox: {
    paddingHorizontal: 25,
    height: 60,
    borderRadius: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginRight: 6,
  },

  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
    paddingHorizontal: 20,
  },

  toggleButton: {
    width: '47%',
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  popupContainer: {
    width: '90%',
    height: 264,
    backgroundColor: 'white',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  popupTitle: {
    fontSize: 40,
    marginBottom: 10,
    color: Colors.red,
    fontFamily: fonts.UrbanistBold,
  },
  popupMessage: {
    fontSize: 18,
    textAlign: 'center',
    color: '#555',
    fontFamily: fonts.UrbanistRegular,
  },
  closeIcon: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: Colors.black,
    width: 25,
    height: 25,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
