import {StyleSheet} from 'react-native';
import fonts from '../../../../utils/Fonts';
import {Colors} from '../../../../utils/Colors';
import {hp, rfs, rhp, rwp, wp} from '../../../../utils/responsivesness';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingBottom: 60,
  },
  title: {
    fontSize: 20,
    fontFamily: fonts.UrbanistBold,
  },
  subText: {
    fontSize: 18,
    marginVertical: 10,
    lineHeight: 20,
    fontFamily: fonts.UrbanistMedium,
  },
  buttonWrapper: {
    alignSelf: 'center',
    marginTop: rhp(20),
  },
  uploadInput: {
    width: '100%',
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1F1F1F',
    borderRadius: 16,
    padding: wp(4),
    marginBottom: rhp(16),
    marginHorizontal: 2,
    alignSelf: 'center',
  },
  uploadPlaceholder: {
    fontSize: rfs(14),
    fontFamily: fonts.UrbanistSemiBold,
    color: '#9E9E9E',
  },
  uploadIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconDivider: {
    width: 1,
    height: rhp(20),
    backgroundColor: Colors.meduimgray,
    marginHorizontal: rwp(10),
  },
  reviewBox: {
    width: '100%',
    backgroundColor: '#1F1F1F',
    borderRadius: 16,
    height: 168,
    padding: rwp(8),
    marginTop: rhp(8),
    marginBottom: rhp(16),
    marginHorizontal: 2,
    alignSelf: 'center',
  },
  reviewLabel: {
    fontSize: rfs(12),
    fontFamily: fonts.UrbanistMedium,
    color: Colors.white,
    marginBottom: rhp(5),
  },
  reviewInput: {
    fontSize: rfs(14),
    fontFamily: fonts.UrbanistSemiBold,
    color: Colors.white,
    minHeight: rhp(100),
    textAlignVertical: 'top',
  },
  remove: {
    position: 'absolute',
    top: 5,
    right: 2,
    padding: 2,
  },
  loaderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  icon: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
  },
  videoWrapper: {
    width: '100%',
    height: 170,
    backgroundColor: Colors.black,
    marginBottom: rhp(16),
    borderRadius: 10,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 2,
    alignSelf: 'center',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  videoButton: {
    width: 50,
    height: 50,
    position: 'absolute',
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#1F1F1F',
    marginBottom: rhp(16),
    marginHorizontal: 2,
  },
  dropdownText: {
    fontFamily: fonts.UrbanistSemiBold,
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 22,
    color: '#9E9E9E',
  },
  dropdownTextSelected: {
    fontFamily: fonts.UrbanistSemiBold,
    fontSize: 16,
    letterSpacing: 0.2,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  fieldLabel: {
    fontSize: rfs(14),
    fontFamily: fonts.UrbanistSemiBold,
    marginBottom: rhp(8),
    marginTop: rhp(16),
  },
  uneditableField: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#1F1F1F',
    marginBottom: rhp(16),
    marginTop: rhp(8),
    opacity: 0.7,
  },
  uneditableText: {
    fontFamily: fonts.UrbanistMedium,
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  guidelinesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#1F1F1F',
    marginBottom: rhp(16),
    marginHorizontal: 2,
  },
  guidelinesText: {
    fontFamily: fonts.UrbanistSemiBold,
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
});
